name: CI com Docker

on:
  push:
    branches: [staging]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Rodar testes dentro do container
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:latest /app/venv/bin/python -m pytest /app/tests/ -v
          docker run --rm -d -p 8080:80 --name test-container ghcr.io/${{ github.repository }}:latest
          sleep 5
          curl -f http://localhost:8080/ || exit 1
          curl -f http://localhost:8080/frase || exit 1
          docker stop test-container

      - name: Deploy simulado no Render com Terraform
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
